import React from 'react';
import styled from 'styled-components';
import { Link } from 'react-router-dom';
import carbonFootprintImg from 'C:/Users/lucis/Climate-Awareness/src/assets/carbon_footprint.png';
import reduceFootprintImg from 'C:/Users/lucis/Climate-Awareness/src/assets/reduce_footprint.png';

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 20px;
  background-color: #adc178;
  color: #004d40;
`;

const Title = styled.h1`
  font-size: 2.5rem;
  font-family: Stencil Std, fantasy;
  margin-bottom: 20px;
`;

const Description = styled.p`
  font-size: 1.2rem;
  margin: 20px 0;
  max-width: 800px;
`;

const Image = styled.img`
  width: 80%;
  max-width: 400px;
  margin: 20px 0;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
`;

const Button = styled(Link)`
  padding: 10px 20px;
  margin: 20px 0;
  background-color: #00796b;
  color: white;
  border: none;
  border-radius: 5px;
  text-decoration: none;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.3s ease, transform 0.3s ease;
  &:hover {
    background-color: #004d40;
    transform: scale(1.05);
  }
`;

const Homepage = () => {
  return (
    <Container>
      <Title>CLIMATE CHANGE AWARENESS</Title>
      <Image src={carbonFootprintImg} alt="Carbon Footprint" />
      <Description>
        A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It's important to reduce our carbon footprint to mitigate the impact of climate change, improve air quality, and preserve our environment for future generations.
      </Description>
      <Image src={reduceFootprintImg} alt="Reduce Footprint" />
      <Description>
        By understanding your carbon footprint, you can take actionable steps to reduce it. Our website helps you track your carbon emissions and provides recommendations on how you can minimize your impact. Let's work together for a greener, more sustainable future.
      </Description>
      <Button to="/">Learn More</Button>
    </Container>
  );
};

export default Homepage;