import React from 'react';
import styled from 'styled-components';
import carbonFootprintImg from '../assets/carbon_footprint.png';
import reduceFootprintImg from '../assets/reduce_footprint.png';
import backgroundVideo from '../assets/background_video.mp4'; 
import Questionnaire from './Questionnaire';  
import navbar from './navbar';

const Container = styled.div`
  background-color: #adc178;
  color: #132a13;
  font-family: 'Arial, sans-serif';
`;

const HeroSection = styled.section`
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
  color: #132a13;
  text-align: center;
  overflow: hidden;
`;

const VideoBackground = styled.video`
  position: absolute;
  top: 50%;
  left: 50%;
  width: 100%;
  height: 100%;
  object-fit: cover;
  transform: translate(-50%, -50%);
  z-index: -1;
`;

const Title = styled.h1`
  font-size: 3.5rem;
  margin-bottom: 20px;
  z-index: 1;
`;

const Subtitle = styled.h2`
  font-size: 2rem;
  margin-bottom: 20px;
  z-index: 1;
`;

const Section = styled.section`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 50px 20px;
  min-height: 100vh;
  text-align: center;
  &:nth-child(odd) {
    background-color: #dde5b6;
  }
  &:nth-child(even) {
    background-color: #adc178;
  }
`;

const Description = styled.p`
  font-size: 1.2rem;
  margin: 20px 0;
  max-width: 800px;
`;

const Image = styled.img`
  width: 80%;
  max-width: 400px;
  margin: 20px 0;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
`;

const Homepage = () => {
  return (
    <Container>
      <navbar />
      <HeroSection>
        <VideoBackground autoPlay loop muted>
          <source src={backgroundVideo} type="video/mp4" />
          Your browser does not support the video tag.
        </VideoBackground>
        <Title>CLIMATE CHANGE AWARENESS</Title>
        <Subtitle>Carbon Footprint Calculator</Subtitle>
      </HeroSection>
      <Section>
        <Subtitle>What is a Carbon Footprint?</Subtitle>
        <Image src={carbonFootprintImg} alt="Carbon Footprint" />
        <Description>
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It's important to reduce our carbon footprint to mitigate the impact of climate change, improve air quality, and preserve our environment for future generations.
        </Description>
      </Section>
      <Section>
        <Subtitle>How to Reduce Your Carbon Footprint</Subtitle>
        <Image src={reduceFootprintImg} alt="Reduce Footprint" />
        <Description>
          By understanding your carbon footprint, you can take actionable steps to reduce it. Our website helps you track your carbon emissions and provides recommendations on how you can minimize your impact. Let's work together for a greener, more sustainable future.
        </Description>
      </Section>
      <Section id="questionnaire-section">
        <Subtitle>Calculate Your Carbon Footprint</Subtitle>
        <Questionnaire />
      </Section>
    </Container>
  );
};

export default Homepage;
